/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// FakeShards implements ShardInterface
type FakeShards struct {
	Fake *FakeOperatorV1alpha1
	ns   string
}

var shardsResource = v1alpha1.SchemeGroupVersion.WithResource("shards")

var shardsKind = v1alpha1.SchemeGroupVersion.WithKind("Shard")

// Get takes name of the shard, and returns the corresponding shard object, and an error if there is any.
func (c *FakeShards) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Shard, err error) {
	emptyResult := &v1alpha1.Shard{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(shardsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Shard), err
}

// List takes label and field selectors, and returns the list of Shards that match those selectors.
func (c *FakeShards) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ShardList, err error) {
	emptyResult := &v1alpha1.ShardList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(shardsResource, shardsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ShardList{ListMeta: obj.(*v1alpha1.ShardList).ListMeta}
	for _, item := range obj.(*v1alpha1.ShardList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shards.
func (c *FakeShards) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(shardsResource, c.ns, opts))

}

// Create takes the representation of a shard and creates it.  Returns the server's representation of the shard, and an error, if there is any.
func (c *FakeShards) Create(ctx context.Context, shard *v1alpha1.Shard, opts v1.CreateOptions) (result *v1alpha1.Shard, err error) {
	emptyResult := &v1alpha1.Shard{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(shardsResource, c.ns, shard, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Shard), err
}

// Update takes the representation of a shard and updates it. Returns the server's representation of the shard, and an error, if there is any.
func (c *FakeShards) Update(ctx context.Context, shard *v1alpha1.Shard, opts v1.UpdateOptions) (result *v1alpha1.Shard, err error) {
	emptyResult := &v1alpha1.Shard{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(shardsResource, c.ns, shard, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Shard), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeShards) UpdateStatus(ctx context.Context, shard *v1alpha1.Shard, opts v1.UpdateOptions) (result *v1alpha1.Shard, err error) {
	emptyResult := &v1alpha1.Shard{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(shardsResource, "status", c.ns, shard, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Shard), err
}

// Delete takes name of the shard and deletes it. Returns an error if one occurs.
func (c *FakeShards) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(shardsResource, c.ns, name, opts), &v1alpha1.Shard{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShards) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(shardsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ShardList{})
	return err
}

// Patch applies the patch and returns the patched shard.
func (c *FakeShards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Shard, err error) {
	emptyResult := &v1alpha1.Shard{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(shardsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Shard), err
}
