/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// FakeRootShards implements RootShardInterface
type FakeRootShards struct {
	Fake *FakeOperatorV1alpha1
	ns   string
}

var rootshardsResource = v1alpha1.SchemeGroupVersion.WithResource("rootshards")

var rootshardsKind = v1alpha1.SchemeGroupVersion.WithKind("RootShard")

// Get takes name of the rootShard, and returns the corresponding rootShard object, and an error if there is any.
func (c *FakeRootShards) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RootShard, err error) {
	emptyResult := &v1alpha1.RootShard{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(rootshardsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RootShard), err
}

// List takes label and field selectors, and returns the list of RootShards that match those selectors.
func (c *FakeRootShards) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RootShardList, err error) {
	emptyResult := &v1alpha1.RootShardList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(rootshardsResource, rootshardsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RootShardList{ListMeta: obj.(*v1alpha1.RootShardList).ListMeta}
	for _, item := range obj.(*v1alpha1.RootShardList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rootShards.
func (c *FakeRootShards) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(rootshardsResource, c.ns, opts))

}

// Create takes the representation of a rootShard and creates it.  Returns the server's representation of the rootShard, and an error, if there is any.
func (c *FakeRootShards) Create(ctx context.Context, rootShard *v1alpha1.RootShard, opts v1.CreateOptions) (result *v1alpha1.RootShard, err error) {
	emptyResult := &v1alpha1.RootShard{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(rootshardsResource, c.ns, rootShard, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RootShard), err
}

// Update takes the representation of a rootShard and updates it. Returns the server's representation of the rootShard, and an error, if there is any.
func (c *FakeRootShards) Update(ctx context.Context, rootShard *v1alpha1.RootShard, opts v1.UpdateOptions) (result *v1alpha1.RootShard, err error) {
	emptyResult := &v1alpha1.RootShard{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(rootshardsResource, c.ns, rootShard, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RootShard), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRootShards) UpdateStatus(ctx context.Context, rootShard *v1alpha1.RootShard, opts v1.UpdateOptions) (result *v1alpha1.RootShard, err error) {
	emptyResult := &v1alpha1.RootShard{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(rootshardsResource, "status", c.ns, rootShard, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RootShard), err
}

// Delete takes name of the rootShard and deletes it. Returns an error if one occurs.
func (c *FakeRootShards) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(rootshardsResource, c.ns, name, opts), &v1alpha1.RootShard{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRootShards) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(rootshardsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RootShardList{})
	return err
}

// Patch applies the patch and returns the patched rootShard.
func (c *FakeRootShards) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RootShard, err error) {
	emptyResult := &v1alpha1.RootShard{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(rootshardsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.RootShard), err
}
