/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	scheme "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/scheme"
)

// BundlesGetter has a method to return a BundleInterface.
// A group's client should implement this interface.
type BundlesGetter interface {
	Bundles(namespace string) BundleInterface
}

// BundleInterface has methods to work with Bundle resources.
type BundleInterface interface {
	Create(ctx context.Context, bundle *operatorv1alpha1.Bundle, opts v1.CreateOptions) (*operatorv1alpha1.Bundle, error)
	Update(ctx context.Context, bundle *operatorv1alpha1.Bundle, opts v1.UpdateOptions) (*operatorv1alpha1.Bundle, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bundle *operatorv1alpha1.Bundle, opts v1.UpdateOptions) (*operatorv1alpha1.Bundle, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorv1alpha1.Bundle, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorv1alpha1.BundleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorv1alpha1.Bundle, err error)
	BundleExpansion
}

// bundles implements BundleInterface
type bundles struct {
	*gentype.ClientWithList[*operatorv1alpha1.Bundle, *operatorv1alpha1.BundleList]
}

// newBundles returns a Bundles
func newBundles(c *OperatorV1alpha1Client, namespace string) *bundles {
	return &bundles{
		gentype.NewClientWithList[*operatorv1alpha1.Bundle, *operatorv1alpha1.BundleList](
			"bundles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operatorv1alpha1.Bundle { return &operatorv1alpha1.Bundle{} },
			func() *operatorv1alpha1.BundleList { return &operatorv1alpha1.BundleList{} },
		),
	}
}
