/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	v1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	scheme "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/scheme"
)

// RootShardsGetter has a method to return a RootShardInterface.
// A group's client should implement this interface.
type RootShardsGetter interface {
	RootShards(namespace string) RootShardInterface
}

// RootShardInterface has methods to work with RootShard resources.
type RootShardInterface interface {
	Create(ctx context.Context, rootShard *v1alpha1.RootShard, opts v1.CreateOptions) (*v1alpha1.RootShard, error)
	Update(ctx context.Context, rootShard *v1alpha1.RootShard, opts v1.UpdateOptions) (*v1alpha1.RootShard, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rootShard *v1alpha1.RootShard, opts v1.UpdateOptions) (*v1alpha1.RootShard, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RootShard, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RootShardList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RootShard, err error)
	RootShardExpansion
}

// rootShards implements RootShardInterface
type rootShards struct {
	*gentype.ClientWithList[*v1alpha1.RootShard, *v1alpha1.RootShardList]
}

// newRootShards returns a RootShards
func newRootShards(c *OperatorV1alpha1Client, namespace string) *rootShards {
	return &rootShards{
		gentype.NewClientWithList[*v1alpha1.RootShard, *v1alpha1.RootShardList](
			"rootshards",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.RootShard { return &v1alpha1.RootShard{} },
			func() *v1alpha1.RootShardList { return &v1alpha1.RootShardList{} }),
	}
}
