/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	scheme "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/scheme"
)

// VirtualWorkspacesGetter has a method to return a VirtualWorkspaceInterface.
// A group's client should implement this interface.
type VirtualWorkspacesGetter interface {
	VirtualWorkspaces(namespace string) VirtualWorkspaceInterface
}

// VirtualWorkspaceInterface has methods to work with VirtualWorkspace resources.
type VirtualWorkspaceInterface interface {
	Create(ctx context.Context, virtualWorkspace *operatorv1alpha1.VirtualWorkspace, opts v1.CreateOptions) (*operatorv1alpha1.VirtualWorkspace, error)
	Update(ctx context.Context, virtualWorkspace *operatorv1alpha1.VirtualWorkspace, opts v1.UpdateOptions) (*operatorv1alpha1.VirtualWorkspace, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualWorkspace *operatorv1alpha1.VirtualWorkspace, opts v1.UpdateOptions) (*operatorv1alpha1.VirtualWorkspace, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorv1alpha1.VirtualWorkspace, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorv1alpha1.VirtualWorkspaceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorv1alpha1.VirtualWorkspace, err error)
	VirtualWorkspaceExpansion
}

// virtualWorkspaces implements VirtualWorkspaceInterface
type virtualWorkspaces struct {
	*gentype.ClientWithList[*operatorv1alpha1.VirtualWorkspace, *operatorv1alpha1.VirtualWorkspaceList]
}

// newVirtualWorkspaces returns a VirtualWorkspaces
func newVirtualWorkspaces(c *OperatorV1alpha1Client, namespace string) *virtualWorkspaces {
	return &virtualWorkspaces{
		gentype.NewClientWithList[*operatorv1alpha1.VirtualWorkspace, *operatorv1alpha1.VirtualWorkspaceList](
			"virtualworkspaces",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *operatorv1alpha1.VirtualWorkspace { return &operatorv1alpha1.VirtualWorkspace{} },
			func() *operatorv1alpha1.VirtualWorkspaceList { return &operatorv1alpha1.VirtualWorkspaceList{} },
		),
	}
}
