//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// VirtualWorkspaceClusterLister can list VirtualWorkspaces across all workspaces, or scope down to a VirtualWorkspaceLister for one workspace.
// All objects returned here must be treated as read-only.
type VirtualWorkspaceClusterLister interface {
	// List lists all VirtualWorkspaces in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error)
	// Cluster returns a lister that can list and get VirtualWorkspaces in one workspace.
	Cluster(clusterName logicalcluster.Name) VirtualWorkspaceLister
	VirtualWorkspaceClusterListerExpansion
}

type virtualWorkspaceClusterLister struct {
	indexer cache.Indexer
}

// NewVirtualWorkspaceClusterLister returns a new VirtualWorkspaceClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewVirtualWorkspaceClusterLister(indexer cache.Indexer) *virtualWorkspaceClusterLister {
	return &virtualWorkspaceClusterLister{indexer: indexer}
}

// List lists all VirtualWorkspaces in the indexer across all workspaces.
func (s *virtualWorkspaceClusterLister) List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*operatorv1alpha1.VirtualWorkspace))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get VirtualWorkspaces.
func (s *virtualWorkspaceClusterLister) Cluster(clusterName logicalcluster.Name) VirtualWorkspaceLister {
	return &virtualWorkspaceLister{indexer: s.indexer, clusterName: clusterName}
}

// VirtualWorkspaceLister can list VirtualWorkspaces across all namespaces, or scope down to a VirtualWorkspaceNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type VirtualWorkspaceLister interface {
	// List lists all VirtualWorkspaces in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error)
	// VirtualWorkspaces returns a lister that can list and get VirtualWorkspaces in one workspace and namespace.
	VirtualWorkspaces(namespace string) VirtualWorkspaceNamespaceLister
	VirtualWorkspaceListerExpansion
}

// virtualWorkspaceLister can list all VirtualWorkspaces inside a workspace or scope down to a VirtualWorkspaceLister for one namespace.
type virtualWorkspaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all VirtualWorkspaces in the indexer for a workspace.
func (s *virtualWorkspaceLister) List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.VirtualWorkspace))
	})
	return ret, err
}

// VirtualWorkspaces returns an object that can list and get VirtualWorkspaces in one namespace.
func (s *virtualWorkspaceLister) VirtualWorkspaces(namespace string) VirtualWorkspaceNamespaceLister {
	return &virtualWorkspaceNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// virtualWorkspaceNamespaceLister helps list and get VirtualWorkspaces.
// All objects returned here must be treated as read-only.
type VirtualWorkspaceNamespaceLister interface {
	// List lists all VirtualWorkspaces in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error)
	// Get retrieves the VirtualWorkspace from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.VirtualWorkspace, error)
	VirtualWorkspaceNamespaceListerExpansion
}

// virtualWorkspaceNamespaceLister helps list and get VirtualWorkspaces.
// All objects returned here must be treated as read-only.
type virtualWorkspaceNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all VirtualWorkspaces in the indexer for a given workspace and namespace.
func (s *virtualWorkspaceNamespaceLister) List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.VirtualWorkspace))
	})
	return ret, err
}

// Get retrieves the VirtualWorkspace from the indexer for a given workspace, namespace and name.
func (s *virtualWorkspaceNamespaceLister) Get(name string) (*operatorv1alpha1.VirtualWorkspace, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(operatorv1alpha1.Resource("virtualworkspaces"), name)
	}
	return obj.(*operatorv1alpha1.VirtualWorkspace), nil
}

// NewVirtualWorkspaceLister returns a new VirtualWorkspaceLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewVirtualWorkspaceLister(indexer cache.Indexer) *virtualWorkspaceScopedLister {
	return &virtualWorkspaceScopedLister{indexer: indexer}
}

// virtualWorkspaceScopedLister can list all VirtualWorkspaces inside a workspace or scope down to a VirtualWorkspaceLister for one namespace.
type virtualWorkspaceScopedLister struct {
	indexer cache.Indexer
}

// List lists all VirtualWorkspaces in the indexer for a workspace.
func (s *virtualWorkspaceScopedLister) List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.VirtualWorkspace))
	})
	return ret, err
}

// VirtualWorkspaces returns an object that can list and get VirtualWorkspaces in one namespace.
func (s *virtualWorkspaceScopedLister) VirtualWorkspaces(namespace string) VirtualWorkspaceNamespaceLister {
	return &virtualWorkspaceScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// virtualWorkspaceScopedNamespaceLister helps list and get VirtualWorkspaces.
type virtualWorkspaceScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VirtualWorkspaces in the indexer for a given workspace and namespace.
func (s *virtualWorkspaceScopedNamespaceLister) List(selector labels.Selector) (ret []*operatorv1alpha1.VirtualWorkspace, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.VirtualWorkspace))
	})
	return ret, err
}

// Get retrieves the VirtualWorkspace from the indexer for a given workspace, namespace and name.
func (s *virtualWorkspaceScopedNamespaceLister) Get(name string) (*operatorv1alpha1.VirtualWorkspace, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(operatorv1alpha1.Resource("virtualworkspaces"), name)
	}
	return obj.(*operatorv1alpha1.VirtualWorkspace), nil
}
