//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// WorkspaceObjectClusterLister can list WorkspaceObjects across all workspaces, or scope down to a WorkspaceObjectLister for one workspace.
// All objects returned here must be treated as read-only.
type WorkspaceObjectClusterLister interface {
	// List lists all WorkspaceObjects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error)
	// Cluster returns a lister that can list and get WorkspaceObjects in one workspace.
	Cluster(clusterName logicalcluster.Name) WorkspaceObjectLister
	WorkspaceObjectClusterListerExpansion
}

type workspaceObjectClusterLister struct {
	indexer cache.Indexer
}

// NewWorkspaceObjectClusterLister returns a new WorkspaceObjectClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewWorkspaceObjectClusterLister(indexer cache.Indexer) *workspaceObjectClusterLister {
	return &workspaceObjectClusterLister{indexer: indexer}
}

// List lists all WorkspaceObjects in the indexer across all workspaces.
func (s *workspaceObjectClusterLister) List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*operatorv1alpha1.WorkspaceObject))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get WorkspaceObjects.
func (s *workspaceObjectClusterLister) Cluster(clusterName logicalcluster.Name) WorkspaceObjectLister {
	return &workspaceObjectLister{indexer: s.indexer, clusterName: clusterName}
}

// WorkspaceObjectLister can list WorkspaceObjects across all namespaces, or scope down to a WorkspaceObjectNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type WorkspaceObjectLister interface {
	// List lists all WorkspaceObjects in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error)
	// WorkspaceObjects returns a lister that can list and get WorkspaceObjects in one workspace and namespace.
	WorkspaceObjects(namespace string) WorkspaceObjectNamespaceLister
	WorkspaceObjectListerExpansion
}

// workspaceObjectLister can list all WorkspaceObjects inside a workspace or scope down to a WorkspaceObjectLister for one namespace.
type workspaceObjectLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all WorkspaceObjects in the indexer for a workspace.
func (s *workspaceObjectLister) List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.WorkspaceObject))
	})
	return ret, err
}

// WorkspaceObjects returns an object that can list and get WorkspaceObjects in one namespace.
func (s *workspaceObjectLister) WorkspaceObjects(namespace string) WorkspaceObjectNamespaceLister {
	return &workspaceObjectNamespaceLister{indexer: s.indexer, clusterName: s.clusterName, namespace: namespace}
}

// workspaceObjectNamespaceLister helps list and get WorkspaceObjects.
// All objects returned here must be treated as read-only.
type WorkspaceObjectNamespaceLister interface {
	// List lists all WorkspaceObjects in the workspace and namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error)
	// Get retrieves the WorkspaceObject from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.WorkspaceObject, error)
	WorkspaceObjectNamespaceListerExpansion
}

// workspaceObjectNamespaceLister helps list and get WorkspaceObjects.
// All objects returned here must be treated as read-only.
type workspaceObjectNamespaceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
	namespace   string
}

// List lists all WorkspaceObjects in the indexer for a given workspace and namespace.
func (s *workspaceObjectNamespaceLister) List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error) {
	err = kcpcache.ListAllByClusterAndNamespace(s.indexer, s.clusterName, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.WorkspaceObject))
	})
	return ret, err
}

// Get retrieves the WorkspaceObject from the indexer for a given workspace, namespace and name.
func (s *workspaceObjectNamespaceLister) Get(name string) (*operatorv1alpha1.WorkspaceObject, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(operatorv1alpha1.Resource("workspaceobjects"), name)
	}
	return obj.(*operatorv1alpha1.WorkspaceObject), nil
}

// NewWorkspaceObjectLister returns a new WorkspaceObjectLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
// - has the cache.NamespaceIndex as an index
func NewWorkspaceObjectLister(indexer cache.Indexer) *workspaceObjectScopedLister {
	return &workspaceObjectScopedLister{indexer: indexer}
}

// workspaceObjectScopedLister can list all WorkspaceObjects inside a workspace or scope down to a WorkspaceObjectLister for one namespace.
type workspaceObjectScopedLister struct {
	indexer cache.Indexer
}

// List lists all WorkspaceObjects in the indexer for a workspace.
func (s *workspaceObjectScopedLister) List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.WorkspaceObject))
	})
	return ret, err
}

// WorkspaceObjects returns an object that can list and get WorkspaceObjects in one namespace.
func (s *workspaceObjectScopedLister) WorkspaceObjects(namespace string) WorkspaceObjectNamespaceLister {
	return &workspaceObjectScopedNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// workspaceObjectScopedNamespaceLister helps list and get WorkspaceObjects.
type workspaceObjectScopedNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all WorkspaceObjects in the indexer for a given workspace and namespace.
func (s *workspaceObjectScopedNamespaceLister) List(selector labels.Selector) (ret []*operatorv1alpha1.WorkspaceObject, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(i interface{}) {
		ret = append(ret, i.(*operatorv1alpha1.WorkspaceObject))
	})
	return ret, err
}

// Get retrieves the WorkspaceObject from the indexer for a given workspace, namespace and name.
func (s *workspaceObjectScopedNamespaceLister) Get(name string) (*operatorv1alpha1.WorkspaceObject, error) {
	key := s.namespace + "/" + name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(operatorv1alpha1.Resource("workspaceobjects"), name)
	}
	return obj.(*operatorv1alpha1.WorkspaceObject), nil
}
