//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	scopedclientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned"
	clientset "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/cluster"
	"github.com/kcp-dev/kcp-operator/sdk/informers/externalversions/internalinterfaces"
	operatorv1alpha1listers "github.com/kcp-dev/kcp-operator/sdk/listers/operator/v1alpha1"
)

// VirtualWorkspaceClusterInformer provides access to a shared informer and lister for
// VirtualWorkspaces.
type VirtualWorkspaceClusterInformer interface {
	Cluster(logicalcluster.Name) VirtualWorkspaceInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() operatorv1alpha1listers.VirtualWorkspaceClusterLister
}

type virtualWorkspaceClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVirtualWorkspaceClusterInformer constructs a new informer for VirtualWorkspace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualWorkspaceClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredVirtualWorkspaceClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualWorkspaceClusterInformer constructs a new informer for VirtualWorkspace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualWorkspaceClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().VirtualWorkspaces().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().VirtualWorkspaces().Watch(context.TODO(), options)
			},
		},
		&operatorv1alpha1.VirtualWorkspace{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualWorkspaceClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredVirtualWorkspaceClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *virtualWorkspaceClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&operatorv1alpha1.VirtualWorkspace{}, f.defaultInformer)
}

func (f *virtualWorkspaceClusterInformer) Lister() operatorv1alpha1listers.VirtualWorkspaceClusterLister {
	return operatorv1alpha1listers.NewVirtualWorkspaceClusterLister(f.Informer().GetIndexer())
}

// VirtualWorkspaceInformer provides access to a shared informer and lister for
// VirtualWorkspaces.
type VirtualWorkspaceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1alpha1listers.VirtualWorkspaceLister
}

func (f *virtualWorkspaceClusterInformer) Cluster(clusterName logicalcluster.Name) VirtualWorkspaceInformer {
	return &virtualWorkspaceInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type virtualWorkspaceInformer struct {
	informer cache.SharedIndexInformer
	lister   operatorv1alpha1listers.VirtualWorkspaceLister
}

func (f *virtualWorkspaceInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *virtualWorkspaceInformer) Lister() operatorv1alpha1listers.VirtualWorkspaceLister {
	return f.lister
}

type virtualWorkspaceScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

func (f *virtualWorkspaceScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorv1alpha1.VirtualWorkspace{}, f.defaultInformer)
}

func (f *virtualWorkspaceScopedInformer) Lister() operatorv1alpha1listers.VirtualWorkspaceLister {
	return operatorv1alpha1listers.NewVirtualWorkspaceLister(f.Informer().GetIndexer())
}

// NewVirtualWorkspaceInformer constructs a new informer for VirtualWorkspace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualWorkspaceInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualWorkspaceInformer(client, resyncPeriod, namespace, indexers, nil)
}

// NewFilteredVirtualWorkspaceInformer constructs a new informer for VirtualWorkspace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualWorkspaceInformer(client scopedclientset.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().VirtualWorkspaces(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().VirtualWorkspaces(namespace).Watch(context.TODO(), options)
			},
		},
		&operatorv1alpha1.VirtualWorkspace{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualWorkspaceScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualWorkspaceInformer(client, resyncPeriod, f.namespace, cache.Indexers{
		cache.NamespaceIndex: cache.MetaNamespaceIndexFunc,
	}, f.tweakListOptions)
}
