apiVersion: operator.kcp.io/v1alpha1
kind: Shard
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: secondary-shard
spec:
  etcd:
    endpoints:
      - http://etcd-shard.default.svc.cluster.local:2379
  rootShard:
    ref:
      name: shard-sample
  deploymentTemplate:
    spec:
      template:
        spec:
          hostAliases:
            # add a hardcoded DNS override to the same IP as in v1alpha1_frontproxy.yaml.
            - ip: "10.96.100.100"
              hostnames:
                - "example.operator.kcp.io"
