apiVersion: operator.kcp.io/v1alpha1
kind: Kubeconfig
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubeconfig-kcp-admin
spec:
  username: kcp-admin
  groups:
    - system:kcp:admin
  validity: 8766h
  secretRef:
    name: sample-kubeconfig
  target:
    frontProxyRef:
      name: frontproxy-sample
    # rootShardRef:
    #   name: shard-sample
