apiVersion: operator.kcp.io/v1alpha1
kind: FrontProxy
metadata:
  labels:
    app.kubernetes.io/name: kcp-operator
    app.kubernetes.io/managed-by: kustomize
  name: frontproxy-sample
spec:
  image:
    tag: eb60348a
  auth:
    # don't drop requests from administrative groups.
    # this shouldn't be enabled in production, but makes testing easier.
    dropGroups: [""]
  rootShard:
    ref:
      name: shard-sample
  serviceTemplate:
    spec:
      # hard code a specific cluster IP, e.g. for a kind setup.
      clusterIP: 10.96.100.100
  certificateTemplates:
    server:
      spec:
        dnsNames:
          # add localhost to the certificate.
          - localhost
        ipAddresses:
          # add localhost IPs to the server certificate.
          # this allows easy port-forward access.
          - 127.0.0.1
          - 127.0.0.2
