/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuthenticationWebhookSpecApplyConfiguration represents a declarative configuration of the AuthenticationWebhookSpec type for use
// with apply.
type AuthenticationWebhookSpecApplyConfiguration struct {
	CacheAuthenticationTTL *v1.Duration `json:"cacheAuthenticationTTL,omitempty"`
	ConfigSecretName       *string      `json:"configSecretName,omitempty"`
	Version                *string      `json:"version,omitempty"`
}

// AuthenticationWebhookSpecApplyConfiguration constructs a declarative configuration of the AuthenticationWebhookSpec type for use with
// apply.
func AuthenticationWebhookSpec() *AuthenticationWebhookSpecApplyConfiguration {
	return &AuthenticationWebhookSpecApplyConfiguration{}
}

// WithCacheAuthenticationTTL sets the CacheAuthenticationTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheAuthenticationTTL field is set to the value of the last call.
func (b *AuthenticationWebhookSpecApplyConfiguration) WithCacheAuthenticationTTL(value v1.Duration) *AuthenticationWebhookSpecApplyConfiguration {
	b.CacheAuthenticationTTL = &value
	return b
}

// WithConfigSecretName sets the ConfigSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigSecretName field is set to the value of the last call.
func (b *AuthenticationWebhookSpecApplyConfiguration) WithConfigSecretName(value string) *AuthenticationWebhookSpecApplyConfiguration {
	b.ConfigSecretName = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AuthenticationWebhookSpecApplyConfiguration) WithVersion(value string) *AuthenticationWebhookSpecApplyConfiguration {
	b.Version = &value
	return b
}
