/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CacheServerSpecApplyConfiguration represents a declarative configuration of the CacheServerSpec type for use
// with apply.
type CacheServerSpecApplyConfiguration struct {
	Etcd    *EtcdConfigApplyConfiguration  `json:"etcd,omitempty"`
	Image   *ImageSpecApplyConfiguration   `json:"image,omitempty"`
	Logging *LoggingSpecApplyConfiguration `json:"logging,omitempty"`
}

// CacheServerSpecApplyConfiguration constructs a declarative configuration of the CacheServerSpec type for use with
// apply.
func CacheServerSpec() *CacheServerSpecApplyConfiguration {
	return &CacheServerSpecApplyConfiguration{}
}

// WithEtcd sets the Etcd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Etcd field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithEtcd(value *EtcdConfigApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.Etcd = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.Image = value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *CacheServerSpecApplyConfiguration) WithLogging(value *LoggingSpecApplyConfiguration) *CacheServerSpecApplyConfiguration {
	b.Logging = value
	return b
}
