/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// CertificatePrivateKeyTemplateApplyConfiguration represents a declarative configuration of the CertificatePrivateKeyTemplate type for use
// with apply.
type CertificatePrivateKeyTemplateApplyConfiguration struct {
	RotationPolicy *operatorv1alpha1.PrivateKeyRotationPolicy `json:"rotationPolicy,omitempty"`
	Encoding       *operatorv1alpha1.PrivateKeyEncoding       `json:"encoding,omitempty"`
	Algorithm      *operatorv1alpha1.PrivateKeyAlgorithm      `json:"algorithm,omitempty"`
	Size           *int                                       `json:"size,omitempty"`
}

// CertificatePrivateKeyTemplateApplyConfiguration constructs a declarative configuration of the CertificatePrivateKeyTemplate type for use with
// apply.
func CertificatePrivateKeyTemplate() *CertificatePrivateKeyTemplateApplyConfiguration {
	return &CertificatePrivateKeyTemplateApplyConfiguration{}
}

// WithRotationPolicy sets the RotationPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RotationPolicy field is set to the value of the last call.
func (b *CertificatePrivateKeyTemplateApplyConfiguration) WithRotationPolicy(value operatorv1alpha1.PrivateKeyRotationPolicy) *CertificatePrivateKeyTemplateApplyConfiguration {
	b.RotationPolicy = &value
	return b
}

// WithEncoding sets the Encoding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Encoding field is set to the value of the last call.
func (b *CertificatePrivateKeyTemplateApplyConfiguration) WithEncoding(value operatorv1alpha1.PrivateKeyEncoding) *CertificatePrivateKeyTemplateApplyConfiguration {
	b.Encoding = &value
	return b
}

// WithAlgorithm sets the Algorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Algorithm field is set to the value of the last call.
func (b *CertificatePrivateKeyTemplateApplyConfiguration) WithAlgorithm(value operatorv1alpha1.PrivateKeyAlgorithm) *CertificatePrivateKeyTemplateApplyConfiguration {
	b.Algorithm = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *CertificatePrivateKeyTemplateApplyConfiguration) WithSize(value int) *CertificatePrivateKeyTemplateApplyConfiguration {
	b.Size = &value
	return b
}
