/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FrontProxySpecApplyConfiguration represents a declarative configuration of the FrontProxySpec type for use
// with apply.
type FrontProxySpecApplyConfiguration struct {
	RootShard *RootShardConfigApplyConfiguration `json:"rootShard,omitempty"`
	Replicas  *int32                             `json:"replicas,omitempty"`
	Auth      *AuthSpecApplyConfiguration        `json:"auth,omitempty"`
}

// FrontProxySpecApplyConfiguration constructs a declarative configuration of the FrontProxySpec type for use with
// apply.
func FrontProxySpec() *FrontProxySpecApplyConfiguration {
	return &FrontProxySpecApplyConfiguration{}
}

// WithRootShard sets the RootShard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootShard field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithRootShard(value *RootShardConfigApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.RootShard = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithReplicas(value int32) *FrontProxySpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *FrontProxySpecApplyConfiguration) WithAuth(value *AuthSpecApplyConfiguration) *FrontProxySpecApplyConfiguration {
	b.Auth = value
	return b
}
