/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OIDCConfigurationApplyConfiguration represents a declarative configuration of the OIDCConfiguration type for use
// with apply.
type OIDCConfigurationApplyConfiguration struct {
	Enabled        *bool   `json:"enabled,omitempty"`
	IssuerURL      *string `json:"issuerURL,omitempty"`
	ClientID       *string `json:"clientID,omitempty"`
	ClientSecret   *string `json:"clientSecret,omitempty"`
	GroupsClaim    *string `json:"groupsClaim,omitempty"`
	UsernameClaim  *string `json:"usernameClaim,omitempty"`
	GroupsPrefix   *string `json:"groupsPrefix,omitempty"`
	UsernamePrefix *string `json:"usernamePrefix,omitempty"`
}

// OIDCConfigurationApplyConfiguration constructs a declarative configuration of the OIDCConfiguration type for use with
// apply.
func OIDCConfiguration() *OIDCConfigurationApplyConfiguration {
	return &OIDCConfigurationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithEnabled(value bool) *OIDCConfigurationApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithIssuerURL sets the IssuerURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuerURL field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithIssuerURL(value string) *OIDCConfigurationApplyConfiguration {
	b.IssuerURL = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithClientID(value string) *OIDCConfigurationApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithClientSecret(value string) *OIDCConfigurationApplyConfiguration {
	b.ClientSecret = &value
	return b
}

// WithGroupsClaim sets the GroupsClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupsClaim field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithGroupsClaim(value string) *OIDCConfigurationApplyConfiguration {
	b.GroupsClaim = &value
	return b
}

// WithUsernameClaim sets the UsernameClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsernameClaim field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithUsernameClaim(value string) *OIDCConfigurationApplyConfiguration {
	b.UsernameClaim = &value
	return b
}

// WithGroupsPrefix sets the GroupsPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupsPrefix field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithGroupsPrefix(value string) *OIDCConfigurationApplyConfiguration {
	b.GroupsPrefix = &value
	return b
}

// WithUsernamePrefix sets the UsernamePrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsernamePrefix field is set to the value of the last call.
func (b *OIDCConfigurationApplyConfiguration) WithUsernamePrefix(value string) *OIDCConfigurationApplyConfiguration {
	b.UsernamePrefix = &value
	return b
}
