/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RootShardCacheConfigApplyConfiguration represents a declarative configuration of the RootShardCacheConfig type for use
// with apply.
type RootShardCacheConfigApplyConfiguration struct {
	Embedded  *EmbeddedCacheConfigurationApplyConfiguration `json:"embedded,omitempty"`
	Reference *v1.LocalObjectReference                      `json:"ref,omitempty"`
}

// RootShardCacheConfigApplyConfiguration constructs a declarative configuration of the RootShardCacheConfig type for use with
// apply.
func RootShardCacheConfig() *RootShardCacheConfigApplyConfiguration {
	return &RootShardCacheConfigApplyConfiguration{}
}

// WithEmbedded sets the Embedded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Embedded field is set to the value of the last call.
func (b *RootShardCacheConfigApplyConfiguration) WithEmbedded(value *EmbeddedCacheConfigurationApplyConfiguration) *RootShardCacheConfigApplyConfiguration {
	b.Embedded = value
	return b
}

// WithReference sets the Reference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reference field is set to the value of the last call.
func (b *RootShardCacheConfigApplyConfiguration) WithReference(value v1.LocalObjectReference) *RootShardCacheConfigApplyConfiguration {
	b.Reference = &value
	return b
}
