/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// RootShardSpecApplyConfiguration represents a declarative configuration of the RootShardSpec type for use
// with apply.
type RootShardSpecApplyConfiguration struct {
	CommonShardSpecApplyConfiguration `json:",inline"`
	External                          *ExternalConfigApplyConfiguration `json:"external,omitempty"`
	Cache                             *CacheConfigApplyConfiguration    `json:"cache,omitempty"`
	Certificates                      *CertificatesApplyConfiguration   `json:"certificates,omitempty"`
}

// RootShardSpecApplyConfiguration constructs a declarative configuration of the RootShardSpec type for use with
// apply.
func RootShardSpec() *RootShardSpecApplyConfiguration {
	return &RootShardSpecApplyConfiguration{}
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithClusterDomain(value string) *RootShardSpecApplyConfiguration {
	b.ClusterDomain = &value
	return b
}

// WithEtcd sets the Etcd field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Etcd field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithEtcd(value *EtcdConfigApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.Etcd = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.Image = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithReplicas(value int32) *RootShardSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *RootShardSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithAudit sets the Audit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audit field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithAudit(value *AuditSpecApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.Audit = value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithAuthorization(value *AuthorizationSpecApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.Authorization = value
	return b
}

// WithCertificateTemplates sets the CertificateTemplates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateTemplates field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithCertificateTemplates(value operatorv1alpha1.CertificateTemplateMap) *RootShardSpecApplyConfiguration {
	b.CertificateTemplates = &value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithServiceTemplate(value *ServiceTemplateApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.ServiceTemplate = value
	return b
}

// WithDeploymentTemplate sets the DeploymentTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentTemplate field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithDeploymentTemplate(value *DeploymentTemplateApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.DeploymentTemplate = value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithExternal(value *ExternalConfigApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.External = value
	return b
}

// WithCache sets the Cache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cache field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithCache(value *CacheConfigApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.Cache = value
	return b
}

// WithCertificates sets the Certificates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certificates field is set to the value of the last call.
func (b *RootShardSpecApplyConfiguration) WithCertificates(value *CertificatesApplyConfiguration) *RootShardSpecApplyConfiguration {
	b.Certificates = value
	return b
}
