/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

// ServiceAccountAuthenticationApplyConfiguration represents a declarative configuration of the ServiceAccountAuthentication type for use
// with apply.
type ServiceAccountAuthenticationApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// ServiceAccountAuthenticationApplyConfiguration constructs a declarative configuration of the ServiceAccountAuthentication type for use with
// apply.
func ServiceAccountAuthentication() *ServiceAccountAuthenticationApplyConfiguration {
	return &ServiceAccountAuthenticationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ServiceAccountAuthenticationApplyConfiguration) WithEnabled(value bool) *ServiceAccountAuthenticationApplyConfiguration {
	b.Enabled = &value
	return b
}
