/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// VirtualWorkspaceInitContainerApplyConfiguration represents a declarative configuration of the VirtualWorkspaceInitContainer type for use
// with apply.
type VirtualWorkspaceInitContainerApplyConfiguration struct {
	Name                *string                      `json:"name,omitempty"`
	Image               *ImageSpecApplyConfiguration `json:"image,omitempty"`
	Command             []string                     `json:"command,omitempty"`
	Args                []string                     `json:"args,omitempty"`
	KubeconfigSecretRef *v1.LocalObjectReference     `json:"kubeconfigSecretRef,omitempty"`
	Resources           *v1.ResourceRequirements     `json:"resources,omitempty"`
}

// VirtualWorkspaceInitContainerApplyConfiguration constructs a declarative configuration of the VirtualWorkspaceInitContainer type for use with
// apply.
func VirtualWorkspaceInitContainer() *VirtualWorkspaceInitContainerApplyConfiguration {
	return &VirtualWorkspaceInitContainerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VirtualWorkspaceInitContainerApplyConfiguration) WithName(value string) *VirtualWorkspaceInitContainerApplyConfiguration {
	b.Name = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *VirtualWorkspaceInitContainerApplyConfiguration) WithImage(value *ImageSpecApplyConfiguration) *VirtualWorkspaceInitContainerApplyConfiguration {
	b.Image = value
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *VirtualWorkspaceInitContainerApplyConfiguration) WithCommand(values ...string) *VirtualWorkspaceInitContainerApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *VirtualWorkspaceInitContainerApplyConfiguration) WithArgs(values ...string) *VirtualWorkspaceInitContainerApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}

// WithKubeconfigSecretRef sets the KubeconfigSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeconfigSecretRef field is set to the value of the last call.
func (b *VirtualWorkspaceInitContainerApplyConfiguration) WithKubeconfigSecretRef(value v1.LocalObjectReference) *VirtualWorkspaceInitContainerApplyConfiguration {
	b.KubeconfigSecretRef = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *VirtualWorkspaceInitContainerApplyConfiguration) WithResources(value v1.ResourceRequirements) *VirtualWorkspaceInitContainerApplyConfiguration {
	b.Resources = &value
	return b
}
