/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// WorkspaceObjectStatusApplyConfiguration represents a declarative configuration of the WorkspaceObjectStatus type for use
// with apply.
type WorkspaceObjectStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	Manifest   *apiextensionsv1.JSON            `json:"manifest,omitempty"`
}

// WorkspaceObjectStatusApplyConfiguration constructs a declarative configuration of the WorkspaceObjectStatus type for use with
// apply.
func WorkspaceObjectStatus() *WorkspaceObjectStatusApplyConfiguration {
	return &WorkspaceObjectStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *WorkspaceObjectStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *WorkspaceObjectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithManifest sets the Manifest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manifest field is set to the value of the last call.
func (b *WorkspaceObjectStatusApplyConfiguration) WithManifest(value apiextensionsv1.JSON) *WorkspaceObjectStatusApplyConfiguration {
	b.Manifest = &value
	return b
}
