/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
)

// WorkspaceObjectSpecApplyConfiguration represents a declarative configuration of the WorkspaceObjectSpec type for use
// with apply.
type WorkspaceObjectSpecApplyConfiguration struct {
	RootShard          *RootShardConfigApplyConfiguration                 `json:"rootShard,omitempty"`
	Workspace          *WorkspaceConfigApplyConfiguration                 `json:"workspace,omitempty"`
	Manifest           *v1.JSON                                           `json:"manifest,omitempty"`
	ManagementPolicies []operatorv1alpha1.WorkspaceObjectManagementPolicy `json:"managementPolicies,omitempty"`
}

// WorkspaceObjectSpecApplyConfiguration constructs a declarative configuration of the WorkspaceObjectSpec type for use with
// apply.
func WorkspaceObjectSpec() *WorkspaceObjectSpecApplyConfiguration {
	return &WorkspaceObjectSpecApplyConfiguration{}
}

// WithRootShard sets the RootShard field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootShard field is set to the value of the last call.
func (b *WorkspaceObjectSpecApplyConfiguration) WithRootShard(value *RootShardConfigApplyConfiguration) *WorkspaceObjectSpecApplyConfiguration {
	b.RootShard = value
	return b
}

// WithWorkspace sets the Workspace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workspace field is set to the value of the last call.
func (b *WorkspaceObjectSpecApplyConfiguration) WithWorkspace(value *WorkspaceConfigApplyConfiguration) *WorkspaceObjectSpecApplyConfiguration {
	b.Workspace = value
	return b
}

// WithManifest sets the Manifest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manifest field is set to the value of the last call.
func (b *WorkspaceObjectSpecApplyConfiguration) WithManifest(value v1.JSON) *WorkspaceObjectSpecApplyConfiguration {
	b.Manifest = &value
	return b
}

// WithManagementPolicies adds the given value to the ManagementPolicies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ManagementPolicies field.
func (b *WorkspaceObjectSpecApplyConfiguration) WithManagementPolicies(values ...operatorv1alpha1.WorkspaceObjectManagementPolicy) *WorkspaceObjectSpecApplyConfiguration {
	for i := range values {
		b.ManagementPolicies = append(b.ManagementPolicies, values[i])
	}
	return b
}
