//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	operatorv1alpha1client "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/typed/operator/v1alpha1"
)

// CacheServersClusterGetter has a method to return a CacheServerClusterInterface.
// A group's cluster client should implement this interface.
type CacheServersClusterGetter interface {
	CacheServers() CacheServerClusterInterface
}

// CacheServerClusterInterface can operate on CacheServers across all clusters,
// or scope down to one cluster and return a CacheServersNamespacer.
type CacheServerClusterInterface interface {
	Cluster(logicalcluster.Path) CacheServersNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*operatorv1alpha1.CacheServerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type cacheServersClusterInterface struct {
	clientCache kcpclient.Cache[*operatorv1alpha1client.OperatorV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *cacheServersClusterInterface) Cluster(clusterPath logicalcluster.Path) CacheServersNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &cacheServersNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all CacheServers across all clusters.
func (c *cacheServersClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*operatorv1alpha1.CacheServerList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CacheServers(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all CacheServers across all clusters.
func (c *cacheServersClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).CacheServers(metav1.NamespaceAll).Watch(ctx, opts)
}

// CacheServersNamespacer can scope to objects within a namespace, returning a operatorv1alpha1client.CacheServerInterface.
type CacheServersNamespacer interface {
	Namespace(string) operatorv1alpha1client.CacheServerInterface
}

type cacheServersNamespacer struct {
	clientCache kcpclient.Cache[*operatorv1alpha1client.OperatorV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *cacheServersNamespacer) Namespace(namespace string) operatorv1alpha1client.CacheServerInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).CacheServers(namespace)
}
