//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	operatorv1alpha1client "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/typed/operator/v1alpha1"
)

// KubeconfigsClusterGetter has a method to return a KubeconfigClusterInterface.
// A group's cluster client should implement this interface.
type KubeconfigsClusterGetter interface {
	Kubeconfigs() KubeconfigClusterInterface
}

// KubeconfigClusterInterface can operate on Kubeconfigs across all clusters,
// or scope down to one cluster and return a KubeconfigsNamespacer.
type KubeconfigClusterInterface interface {
	Cluster(logicalcluster.Path) KubeconfigsNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*operatorv1alpha1.KubeconfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type kubeconfigsClusterInterface struct {
	clientCache kcpclient.Cache[*operatorv1alpha1client.OperatorV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *kubeconfigsClusterInterface) Cluster(clusterPath logicalcluster.Path) KubeconfigsNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &kubeconfigsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all Kubeconfigs across all clusters.
func (c *kubeconfigsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*operatorv1alpha1.KubeconfigList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Kubeconfigs(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all Kubeconfigs across all clusters.
func (c *kubeconfigsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).Kubeconfigs(metav1.NamespaceAll).Watch(ctx, opts)
}

// KubeconfigsNamespacer can scope to objects within a namespace, returning a operatorv1alpha1client.KubeconfigInterface.
type KubeconfigsNamespacer interface {
	Namespace(string) operatorv1alpha1client.KubeconfigInterface
}

type kubeconfigsNamespacer struct {
	clientCache kcpclient.Cache[*operatorv1alpha1client.OperatorV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *kubeconfigsNamespacer) Namespace(namespace string) operatorv1alpha1client.KubeconfigInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).Kubeconfigs(namespace)
}
