//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The kcp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"

	operatorv1alpha1 "github.com/kcp-dev/kcp-operator/sdk/apis/operator/v1alpha1"
	operatorv1alpha1client "github.com/kcp-dev/kcp-operator/sdk/clientset/versioned/typed/operator/v1alpha1"
)

// RootShardsClusterGetter has a method to return a RootShardClusterInterface.
// A group's cluster client should implement this interface.
type RootShardsClusterGetter interface {
	RootShards() RootShardClusterInterface
}

// RootShardClusterInterface can operate on RootShards across all clusters,
// or scope down to one cluster and return a RootShardsNamespacer.
type RootShardClusterInterface interface {
	Cluster(logicalcluster.Path) RootShardsNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*operatorv1alpha1.RootShardList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type rootShardsClusterInterface struct {
	clientCache kcpclient.Cache[*operatorv1alpha1client.OperatorV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *rootShardsClusterInterface) Cluster(clusterPath logicalcluster.Path) RootShardsNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &rootShardsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all RootShards across all clusters.
func (c *rootShardsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*operatorv1alpha1.RootShardList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).RootShards(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all RootShards across all clusters.
func (c *rootShardsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).RootShards(metav1.NamespaceAll).Watch(ctx, opts)
}

// RootShardsNamespacer can scope to objects within a namespace, returning a operatorv1alpha1client.RootShardInterface.
type RootShardsNamespacer interface {
	Namespace(string) operatorv1alpha1client.RootShardInterface
}

type rootShardsNamespacer struct {
	clientCache kcpclient.Cache[*operatorv1alpha1client.OperatorV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *rootShardsNamespacer) Namespace(namespace string) operatorv1alpha1client.RootShardInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).RootShards(namespace)
}
