name: Documentation

on:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
  # Pushes to branches do the full build + deployment
  push:
    branches:
      - main
      - "release-*"
    paths:
      - "docs/**"
      - "sdk/apis/**"
      - ".github/workflows/docs-gen-and-push.yaml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  generate-and-push:
    name: Generate and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2

      - run: git fetch origin gh-pages
      - run: git fetch origin '+refs/tags/v*:refs/tags/v*' --no-tags

      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # tag=v5.4.0
        with:
          go-version: v1.24.3
          cache: true

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 #tag=v5.5.0
        with:
          python-version: '3.10'
          cache: 'pip'

      # mike does not support giving CLI flags for mkdocs, but we also do not
      # want to permanently enable strict mode, so here we enable it just for this
      # task
      - run: |
          echo "strict: true" >> docs/mkdocs.yml

      - run: make generate-api-docs deploy-docs
